### ISSUE TITLE
Error trying to convert scAlign object to Seurat

### ISSUE THREAD

**Issue by achamess** [quon-titative-biology/examples#1]
I'm running through this tutorial with 4 10x datasets:
https://github.com/quon-titative-biology/examples/blob/master/scAlign_multiway_alignment/scAlign_multiway_pancreas.md

I advanced successfully through the `scAlignMulti` step. But now I'm catching an error when trying to convert to a Seurat object.

```
scAlignSeuratObj = as.Seurat(scAlignCeA, counts="counts", scale.data="scale.data")
```
I'm getting:
```
Error in intI(j, n = d[2], dn[[2]], give.dn = FALSE) : invalid character indexing
```

Any thoughts?

**Comment by UCDNJJ** [comment]
Hi,

Great to hear you've successfully aligned your 4 10x datasets! 

I've encountered the same error before with Seurat's conversion functions such as `as.Seurat`. I believe the error was caused by the names of features (genes) or cells not being characters. I tried reproducing the error but was unable to when using `as.Seurat` with Seurat 3.1.1. Could you perhaps trying updating Seurat (If not already at 3.1.1)? 

Otherwise, you could try initializing an empty Seurat object and fill the data/reduction slots manually.

**Comment by achamess** [comment]
Thank you. I am using Seurat 3.1.1. Would you mind demonstrating how to initialize an empty Seurat object and then filling the data/reduction slots, as you described?

**Comment by UCDNJJ** [comment]
Of course, following the pancreas alignment tutorial here is an example of creating and filling a Seurat object manually with data/alignements from a SingleCellExperiment object. 
```## Create a Seurat Object and manually fill it with assay data
scAlignSeuratObj = CreateSeuratObject(counts=assay(scAlignPancreas, "counts"))
scAlignSeuratObj = SetAssayData(scAlignSeuratObj, slot="data", new.data=assay(scAlignPancreas, "logcounts"), assay="RNA")
scAlignSeuratObj = SetAssayData(scAlignSeuratObj, slot="scale.data", new.data=assay(scAlignPancreas, "scale.data"), assay="RNA")

## Print available reductions
reducedDims(scAlignPancreas)
## Manually set the reduction
scAlignSeuratObj[["ALIGNEDGENE"]] <- CreateDimReducObject(embeddings = reducedDim(scAlignPancreas, "ALIGNED-GENE"), key = "ALIGNEDGENE", assay = DefaultAssay(scAlignSeuratObj))
## We can now use the name "ALIGNEDGENE" in any downstream Seurat analysis
```
Hope this helps,
Nelson
