### ISSUE TITLE
UMAP input suggestions?

### ISSUE THREAD

**Issue by tbrunetti** [quon-titative-biology/examples#4]
I have run an alignment step using scAlignMulti and I see there is a new dimension reduction called ALIGNED.MultiCCA.  I can see the t-SNE just fine, but what would you suggest to plot this in UMAP?

Also, I am assuming this is another dimension reduction method, therefore, there is no need for me to perform any PC analysis, except for visualization on my own to determine if I should regress out any covars, correct?  

I have tried running the RunUMAP (the Seurat function in R, however, my primary coding language is in Python so can I export the data and run it in Python using that UMAP?) call without much luck.  Would you mind providing an example of how to use this scAlignMulti object or after it has been converted into a Seurat or single cell experiment object into UMAP? 

Thanks!
Tonya

**Comment by UCDNJJ** [comment]
Right, there is no need to PC the output of scAlign ("ALIGNED.MultiCCA") since our neural network has already learned a low dimensional embedding which is shared across all datasets.

UMAP or tSNE both are fine to produce visualizations. UMAP would definitely be worth trying since it starts at a better initialization point than tSNE: https://www.biorxiv.org/content/10.1101/2019.12.19.877522v1 

If you would like to use Seurat on the resulting embedding produced by scAlign then I would suggest putting the scAlign embedding into the Seurat object like this:

SeuratObj[["scAlign"]] <- CreateDimReducObject(embeddings = ALIGNED.MultiCCA, key = "scAlign_", assay = DefaultAssay(SeuratObj))

Then you are free to use RunUMAP on the scAlign embeddings! Just be sure to specify scAlign as the reduction when calling RunUMAP.

Let me know if this doesn't work!
